type EnvironmentVariables = {
  PORT?: string;
  NODE_ENV?: string;
  DATABASE_URL?: string;
  FRONTEND_ALLOWED_ORIGINS?: string;
  TRUST_PROXY?: string;
  ENABLE_SWAGGER?: string;
  REQUEST_BODY_LIMIT?: string;
  HTTP_KEEP_ALIVE_TIMEOUT_MS?: string;
  HTTP_HEADERS_TIMEOUT_MS?: string;
  RATE_LIMIT_ADAPTER?: string;
  RATE_LIMIT_REDIS_URL?: string;
  RATE_LIMIT_STRICT?: string;
  REALTIME_ADAPTER?: string;
  REALTIME_REDIS_URL?: string;
  REALTIME_STRICT?: string;
  GRACEFUL_SHUTDOWN_TIMEOUT_MS?: string;
  DRIVER_RESERVATION_EXPIRY_SWEEP_INTERVAL_MS?: string;
  DRIVER_RESERVATION_EXPIRY_MAX_SILENCE_MS?: string;
  HEALTH_WATCHDOG_INTERVAL_MS?: string;
  HEALTH_WATCHDOG_ALERT_COOLDOWN_MS?: string;
  HEALTH_INCIDENT_HISTORY_LIMIT?: string;
  DISPATCH_SIGNAL_LOOKBACK_HOURS?: string;
  DISPATCH_SIGNAL_HALF_LIFE_HOURS?: string;
  DISPATCH_DECLINE_COOLDOWN_MINUTES?: string;
  DISPATCH_SIGNAL_HISTORY_LIMIT?: string;
  FEATURE_FLAG_PAYMENTS?: string;
  FEATURE_FLAG_PAYMENTS_ALLOWLIST?: string;
  FEATURE_FLAG_PRICING?: string;
  FEATURE_FLAG_PRICING_ALLOWLIST?: string;
  FEATURE_FLAG_REALTIME?: string;
  FEATURE_FLAG_REALTIME_ALLOWLIST?: string;
  FEATURE_FLAG_DRIVER_ONBOARDING?: string;
  FEATURE_FLAG_DRIVER_ONBOARDING_ALLOWLIST?: string;
  FEATURE_FLAG_VOICE?: string;
  FEATURE_FLAG_VOICE_ALLOWLIST?: string;
  PAYMENTS_PROVIDER?: string;
  PAYMENTS_CURRENCY?: string;
  PAYMENTS_WEBHOOK_SECRET?: string;
  PAYMENTS_DEFAULT_REDIRECT_URL?: string;
  PAYMENTS_DEFAULT_WEBHOOK_URL?: string;
  FLUTTERWAVE_PUBLIC_KEY?: string;
  FLUTTERWAVE_SECRET_KEY?: string;
  FLUTTERWAVE_WEBHOOK_SECRET_HASH?: string;
  CINETPAY_SITE_ID?: string;
  CINETPAY_API_KEY?: string;
  CINETPAY_SECRET_KEY?: string;
  DOCUMENT_SIGNING_SECRET?: string;
  DOCUMENT_UPLOAD_BASE_URL?: string;
  DOCUMENT_VIEW_BASE_URL?: string;
  DOCUMENT_LINK_TTL_SECONDS?: string;
};

export function validateEnvironment(config: EnvironmentVariables) {
  const isTestEnvironment = config.NODE_ENV === 'test';

  if (!config.DATABASE_URL && !isTestEnvironment) {
    throw new Error('DATABASE_URL is required to start the Mobilis backend.');
  }

  return {
    PORT: config.PORT ?? '3000',
    NODE_ENV: config.NODE_ENV ?? 'development',
    DATABASE_URL:
      config.DATABASE_URL ??
      'postgresql://postgres:postgres@localhost:5433/mobilis?schema=public',
    FRONTEND_ALLOWED_ORIGINS:
      config.FRONTEND_ALLOWED_ORIGINS ??
      'http://localhost:3001,http://localhost:8081',
    TRUST_PROXY: config.TRUST_PROXY ?? 'false',
    ENABLE_SWAGGER: config.ENABLE_SWAGGER ?? 'true',
    REQUEST_BODY_LIMIT: config.REQUEST_BODY_LIMIT ?? '256kb',
    HTTP_KEEP_ALIVE_TIMEOUT_MS: config.HTTP_KEEP_ALIVE_TIMEOUT_MS ?? '65000',
    HTTP_HEADERS_TIMEOUT_MS: config.HTTP_HEADERS_TIMEOUT_MS ?? '66000',
    RATE_LIMIT_ADAPTER: config.RATE_LIMIT_ADAPTER ?? 'in-memory',
    RATE_LIMIT_REDIS_URL: config.RATE_LIMIT_REDIS_URL ?? '',
    RATE_LIMIT_STRICT: config.RATE_LIMIT_STRICT ?? 'false',
    REALTIME_ADAPTER: config.REALTIME_ADAPTER ?? 'in-memory',
    REALTIME_REDIS_URL: config.REALTIME_REDIS_URL ?? '',
    REALTIME_STRICT: config.REALTIME_STRICT ?? 'false',
    GRACEFUL_SHUTDOWN_TIMEOUT_MS:
      config.GRACEFUL_SHUTDOWN_TIMEOUT_MS ?? '15000',
    DRIVER_RESERVATION_EXPIRY_SWEEP_INTERVAL_MS:
      config.DRIVER_RESERVATION_EXPIRY_SWEEP_INTERVAL_MS ?? '5000',
    DRIVER_RESERVATION_EXPIRY_MAX_SILENCE_MS:
      config.DRIVER_RESERVATION_EXPIRY_MAX_SILENCE_MS ?? '30000',
    HEALTH_WATCHDOG_INTERVAL_MS: config.HEALTH_WATCHDOG_INTERVAL_MS ?? '15000',
    HEALTH_WATCHDOG_ALERT_COOLDOWN_MS:
      config.HEALTH_WATCHDOG_ALERT_COOLDOWN_MS ?? '60000',
    HEALTH_INCIDENT_HISTORY_LIMIT: config.HEALTH_INCIDENT_HISTORY_LIMIT ?? '12',
    DISPATCH_SIGNAL_LOOKBACK_HOURS:
      config.DISPATCH_SIGNAL_LOOKBACK_HOURS ?? '72',
    DISPATCH_SIGNAL_HALF_LIFE_HOURS:
      config.DISPATCH_SIGNAL_HALF_LIFE_HOURS ?? '18',
    DISPATCH_DECLINE_COOLDOWN_MINUTES:
      config.DISPATCH_DECLINE_COOLDOWN_MINUTES ?? '20',
    DISPATCH_SIGNAL_HISTORY_LIMIT: config.DISPATCH_SIGNAL_HISTORY_LIMIT ?? '48',
    FEATURE_FLAG_PAYMENTS: config.FEATURE_FLAG_PAYMENTS ?? 'on',
    FEATURE_FLAG_PAYMENTS_ALLOWLIST:
      config.FEATURE_FLAG_PAYMENTS_ALLOWLIST ?? '',
    FEATURE_FLAG_PRICING: config.FEATURE_FLAG_PRICING ?? 'on',
    FEATURE_FLAG_PRICING_ALLOWLIST: config.FEATURE_FLAG_PRICING_ALLOWLIST ?? '',
    FEATURE_FLAG_REALTIME: config.FEATURE_FLAG_REALTIME ?? 'on',
    FEATURE_FLAG_REALTIME_ALLOWLIST:
      config.FEATURE_FLAG_REALTIME_ALLOWLIST ?? '',
    FEATURE_FLAG_DRIVER_ONBOARDING:
      config.FEATURE_FLAG_DRIVER_ONBOARDING ?? 'on',
    FEATURE_FLAG_DRIVER_ONBOARDING_ALLOWLIST:
      config.FEATURE_FLAG_DRIVER_ONBOARDING_ALLOWLIST ?? '',
    FEATURE_FLAG_VOICE: config.FEATURE_FLAG_VOICE ?? 'on',
    FEATURE_FLAG_VOICE_ALLOWLIST: config.FEATURE_FLAG_VOICE_ALLOWLIST ?? '',
    PAYMENTS_PROVIDER: config.PAYMENTS_PROVIDER ?? 'flutterwave',
    PAYMENTS_CURRENCY: config.PAYMENTS_CURRENCY ?? 'XOF',
    PAYMENTS_WEBHOOK_SECRET:
      config.PAYMENTS_WEBHOOK_SECRET ?? 'mobilis_dev_webhook_secret',
    PAYMENTS_DEFAULT_REDIRECT_URL:
      config.PAYMENTS_DEFAULT_REDIRECT_URL ?? 'http://localhost:8081/book',
    PAYMENTS_DEFAULT_WEBHOOK_URL:
      config.PAYMENTS_DEFAULT_WEBHOOK_URL ??
      'http://localhost:3000/api/v1/payments/webhooks',
    FLUTTERWAVE_PUBLIC_KEY: config.FLUTTERWAVE_PUBLIC_KEY ?? '',
    FLUTTERWAVE_SECRET_KEY: config.FLUTTERWAVE_SECRET_KEY ?? '',
    FLUTTERWAVE_WEBHOOK_SECRET_HASH:
      config.FLUTTERWAVE_WEBHOOK_SECRET_HASH ?? '',
    CINETPAY_SITE_ID: config.CINETPAY_SITE_ID ?? '',
    CINETPAY_API_KEY: config.CINETPAY_API_KEY ?? '',
    CINETPAY_SECRET_KEY: config.CINETPAY_SECRET_KEY ?? '',
    DOCUMENT_SIGNING_SECRET:
      config.DOCUMENT_SIGNING_SECRET ?? 'mobilis_dev_document_secret',
    DOCUMENT_UPLOAD_BASE_URL:
      config.DOCUMENT_UPLOAD_BASE_URL ?? 'https://storage.mobilis.local/upload',
    DOCUMENT_VIEW_BASE_URL:
      config.DOCUMENT_VIEW_BASE_URL ?? 'https://storage.mobilis.local/view',
    DOCUMENT_LINK_TTL_SECONDS: config.DOCUMENT_LINK_TTL_SECONDS ?? '900',
  };
}
