export const ACCESS_TOKEN_TTL_IN_MINUTES = 15;
export const SESSION_TTL_IN_DAYS = 30;
export const REFRESH_TOKEN_TTL_IN_DAYS = SESSION_TTL_IN_DAYS;
export const DEFAULT_WALLET_CURRENCY = 'XOF';
export const SESSION_LAST_SEEN_UPDATE_INTERVAL_IN_MINUTES = 5;
export const PHONE_OTP_TTL_IN_MINUTES = 5;
export const PHONE_OTP_MAX_VERIFY_ATTEMPTS = 5;
export const PHONE_OTP_MAX_ACTIVE_CODES_PER_PHONE = 3;
