// ── @orbi/api — public surface ────────────────────────────────────────────────
// All domain re-exports and sub-module re-exports live here so that existing
// imports of "@orbi/api" continue to work without changes.

// ── @orbi/domain re-exports ───────────────────────────────────────────────────
export type {
  AdminMetric,
  ApiDemandLevel,
  ApiDistrictProfile,
  ApiMarketZone,
  ApiPaymentMethod,
  ApiPricingCity,
  ApiRoadCondition,
  ApiServiceTier,
  ApiTrafficLevel,
  ApiUserRole,
  ApiVehicleType,
  ApiWeatherCondition,
  BookingDraft,
  BurkinaPricingCityPreset,
  CoordinatePoint,
  Coordinates,
  DemandLevel,
  DriverOffer,
  MarketZone,
  Money,
  PaymentMethod,
  Place,
  PricingEstimate,
  RideOption,
  RideRequestLifecycleStatus,
  RideStatus,
  ServiceTier,
  TripLifecycleStatus,
  UserRole,
  VehicleCategory,
  VoiceSuggestion,
} from "@orbi/domain";
export {
  activeRideRequestLifecycleStatuses,
  activeTripLifecycleStatuses,
  allowedTripLifecycleTransitions,
  apiDemandLevels,
  apiDistrictProfiles,
  apiMarketZones,
  apiPaymentMethods,
  apiPricingCities,
  apiRoadConditions,
  apiServiceTiers,
  apiTrafficLevels,
  apiVehicleTypes,
  apiWeatherConditions,
  canTransitionTripLifecycleStatus,
  calculateDistanceKm,
  defaultBookingDraft,
  burkinaPricingCityPresets,
  demandLevels,
  estimateDurationMinutes,
  hasDefinedCoordinates,
  isActiveRideRequestLifecycleStatus,
  isActiveTripLifecycleStatus,
  isPickupCodeVisibleTripLifecycleStatus,
  marketZones,
  orbiBrand,
  paymentMethods,
  pickupCodeVisibleTripLifecycleStatuses,
  roundDistanceKm,
  resolveBurkinaPricingPresetForPlace,
  rideRequestLifecycleStatuses,
  rideStatuses,
  serviceTiers,
  tripLifecycleStatuses,
  userRoles,
  vehicleCategories,
} from "@orbi/domain";

// ── Sub-module re-exports ─────────────────────────────────────────────────────

export type {
  ApiClientOptions,
  RequestOptions,
  NetworkRetryOptions,
} from "./client";
export {
  OrbiApiError,
  isOrbiApiError,
  extractApiErrorMessage,
  withNetworkRetry,
  OrbiApiClient,
  createOrbiApiClient,
} from "./client";

export type {
  OrbiClientErrorSurface,
  OrbiClientErrorClassification,
  OrbiClientAppRole,
  OrbiClientErrorReport,
  SubmitMobileErrorReportsPayload,
  SubmitMobileErrorReportsResponse,
} from "./error-reporting";
export {
  normalizeOrbiClientErrorReportQueue,
  classifyOrbiClientError,
  createOrbiClientErrorReport,
  createOrbiClientErrorReportFromClassification,
  resolveMobileRenderCrashSurface,
} from "./error-reporting";

export {
  apiConfig,
  apiRoutes,
  buildRealtimeStreamUrl,
  riderRideOptions,
  driverOffers,
  adminMetrics,
  voiceSuggestions,
} from "./routes";

export type {
  SignUpPayload,
  SignInPayload,
  SignUpApiPayload,
  AuthSessionResponse,
  CurrentUserResponse,
  AuthenticatedApiContext,
  SessionStorageAdapter,
  SignOutResponse,
  TicketCategory,
  SupportTicketStatus,
  SupportTicket,
  CreateSupportTicketPayload,
  CreateSupportTicketResponse,
  MySupportTicketsResponse,
  PromoValidationResponse,
} from "./auth";
export {
  signInWithApi,
  signUpWithApi,
  fetchCurrentUser,
  authenticateAndFetchCurrentUser,
  restoreOrAuthenticateSession,
  restorePersistedSession,
  persistSessionToken,
  clearPersistedSession,
  signOutWithApi,
  registerPushTokenWithApi,
  createSupportTicketWithApi,
  getMySupportTicketsWithApi,
  validatePromoCodeWithApi,
} from "./auth";

export type {
  AdminJobQueueKind,
  HealthCheckResponse,
  AdminPreviewResponse,
  AdminOverviewResponse,
  AdminOperationalKpisResponse,
  AdminLiveOpsResponse,
  AdminTripsAuditResponse,
  AdminTripAuditRiskResolutionResponse,
  AdminLaunchReadinessResponse,
  AdminLaunchReadinessActionAcknowledgementResponse,
  SupportTicketQueueResponse,
  SupportTicketUpdateResponse,
  AdminRidersResponse,
  AdminRiderStatusResponse,
  AdminDriversResponse,
  AdminDriverWalletsResponse,
  AdminFinanceDashboardResponse,
  AdminDriverPayoutResponse,
  AdminDriverWalletRecoveryAdjustmentResponse,
  AdminPaymentWebhookEventsResponse,
  AdminPaymentWebhookEventDetailResponse,
  AdminPaymentWebhookInvestigationResponse,
  AdminPaymentWebhookReplayResponse,
  AdminPaymentAttemptProviderVerificationResponse,
  AdminPaymentAttemptRefundResponse,
  DriverOnboardingQueueResponse,
  DriverOnboardingExportHistoryResponse,
  DriverOnboardingReviewUpdateResponse,
  AdminFeatureFlagsResponse,
  AdminDispatchSettingsResponse,
  AdminPricingCalibrationResponse,
  AdminJobQueueResponse,
  AdminJobQueueRequeueResponse,
  DriverDocumentUploadLinksResponse,
  DriverDocumentViewLinkResponse,
  DriverDocumentObjectVerificationResponse,
  PromoCodeItem,
  ListAdminPromoCodesResponse,
  CreateAdminPromoCodePayload,
} from "./admin";
export {
  fetchAdminPreview,
  fetchAdminOverview,
  fetchAdminOperationalKpis,
  fetchAdminLiveOps,
  fetchAdminTripsAudit,
  resolveAdminTripAuditRisk,
  fetchAdminJobQueue,
  requeueAdminJobQueueEntry,
  fetchAdminLaunchReadiness,
  acknowledgeAdminLaunchReadinessAction,
  fetchAdminSupportTickets,
  fetchAdminDrivers,
  fetchAdminRiders,
  updateAdminRiderStatus,
  fetchAdminDriverWallets,
  fetchAdminFinanceDashboard,
  prepareAdminDriverWalletPayout,
  recordAdminDriverWalletRecoveryAdjustment,
  markAdminDriverPayoutPaid,
  buildAdminDriverPayoutSettlementCsvUrl,
  buildAdminDriverPayoutSettlementPdfUrl,
  updateAdminSupportTicket,
  fetchAdminDriverOnboardingQueue,
  fetchAdminDriverOnboardingExportCsv,
  fetchAdminDriverOnboardingExportHistory,
  fetchAdminTripsExportCsv,
  fetchAdminFeatureFlags,
  fetchAdminDispatchSettings,
  fetchAdminPricingCalibration,
  fetchAdminPaymentWebhookEvents,
  fetchAdminPaymentWebhookEventDetail,
  startAdminPaymentWebhookInvestigation,
  replayAdminPaymentWebhookEvent,
  verifyAdminPaymentAttemptWithProvider,
  refundAdminPaymentAttempt,
  updateAdminDispatchSettings,
  fetchHealthCheck,
  acknowledgeAdminHealthIncident,
  muteAdminHealthIncident,
  updateAdminDriverOnboardingReview,
  suspendAdminDriver,
  reactivateAdminDriver,
  fetchAdminDriverDocumentViewLink,
  updateAdminDriverDocumentObjectVerification,
  verifyAdminDriverDocumentObjectWithProvider,
  listAdminPromoCodes,
  createAdminPromoCode,
  deactivateAdminPromoCode,
} from "./admin";

export type {
  DriverFatigueStatus,
  DriverProfileResponse,
  DriverAvailabilityResponse,
  DriverPresenceResponse,
  DriverOnboardingResponse,
  DriverEarningsResponse,
  DriverOfferDeclineResponse,
  NearbyDriverMarker,
  NearbyDriversResponse,
} from "./drivers";
export {
  fetchNearbyDrivers,
  fetchDriverPreviewOffers,
  fetchDriverProfile,
  fetchDriverOnboarding,
  upsertDriverOnboarding,
  requestDriverDocumentUploadLinks,
  fetchDriverEarnings,
  fetchDriverOffers,
  declineDriverOfferWithApi,
  updateDriverAvailabilityWithApi,
  updateDriverPresenceWithApi,
} from "./drivers";

export type {
  RiderProfileResponse,
  SavedPlaceMutationResponse,
  TrustedContactMutationResponse,
  TrustedContactRosterMutationResponse,
  TrustedContactDeleteResponse,
  SavedPlaceDeleteResponse,
  WalletBalanceResponse,
  WalletTopUpResponse,
  WalletTopUpHistoryItem,
} from "./riders";
export {
  fetchRiderProfile,
  createSavedPlaceWithApi,
  updateTrustedContactWithApi,
  createTrustedContactWithApi,
  updateTrustedContactEntryWithApi,
  deleteTrustedContactWithApi,
  updateSavedPlaceWithApi,
  deleteSavedPlaceWithApi,
  fetchWalletBalanceWithApi,
  initiateWalletTopUpWithApi,
  fetchWalletTopUpHistoryWithApi,
} from "./riders";

export type {
  MyTripsResponse,
  TripLifecycleResponse,
  TripDetailResponse,
  TripShareLinkResponse,
  TripRoutePositionResponse,
  SharedTripResponse,
  TripIncidentResponse,
  TripSafetySosResponse,
  TripRatingResponse,
  CreateRideRequestPayload,
  RideRequestResponse,
  RideRequestLifecycleResponse,
  RideOptionsPreviewResponse,
  VoiceLocationIntentResponse,
  PricingEstimateQuery,
  ScheduledRideStatus,
  ScheduledRide,
  CreateScheduledRidePayload,
} from "./trips";
export {
  toApiVehicleType,
  toApiServiceTier,
  toApiPaymentMethod,
  fetchMyTrips,
  fetchTripDetail,
  createTripShareLinkWithApi,
  recordTripRoutePositionWithApi,
  fetchSharedTripWithApi,
  acceptRideRequestWithApi,
  updateTripStatusWithApi,
  verifyPickupCodeWithApi,
  reportTripIncidentWithApi,
  triggerTripSafetySosWithApi,
  rateTripWithApi,
  fetchRideOptionsPreview,
  fetchPricingEstimate,
  createRideRequestWithApi,
  cancelRideRequestWithApi,
  resolveVoiceLocationIntentWithApi,
  createScheduledRideWithApi,
  fetchMyScheduledRidesWithApi,
  cancelScheduledRideWithApi,
} from "./trips";

export type {
  CheckoutIntentPayload,
  CheckoutIntentResponse,
} from "./payments";
export { createCheckoutIntentWithApi } from "./payments";

// ── Error reporting API function (uses both error-reporting + client) ─────────
export { submitMobileErrorReportsWithApi } from "./error-reporting-api";
